---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 21.03.19 22:08
---

local spells = {}
spells["Necromancy"] = {"UndeadSummon","RaiseDead","DeathlyRecruit","Exhumation","DarkSacrifice","Possess"}
spells["Elemental"] = {"ElementalSummon"}
spells["Common"] = {"Bless","TownPortal","ElementalSummon","RaiseDead","BodyArmor"}
spells["Combat"] = {"DieHard","Dash","BodyArmor","Smash"}
spells["Rogue"] = {"Cloak"}

return spells