---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 04.08.18 18:14
---

local RPD = require "scripts/lib/commonClasses"
local actor = require "scripts/lib/actor"
local storage = require "scripts/lib/storage"
local mob = require "scripts/lib/mob"

local dungeonEntrance = {13, 4}
local shopEntrance = {18, 16}

local lastWarningTime = 0
local time = 0

local ShadowType = {Shadow=true,MazeShadow=true,DarkElemental=true,ShadowLord=true,Lich=true,DreadKnight=true,DeadKnight=true,DarkMage=true}
local IceType = {Kobold=true,IceElemental=true,KoboldIcemancer=true,ColdSpirit=true,IceGuardian=true,IceGuardianCore=true,IceMage=true}
local SpiderType = {SpiderMind=true,SpiderGuard=true,SpiderQueen=true,SpiderServant=true,SpiderExploding=true,SpiderMindAmber=true,UndeadSpiderMutant=true}
local FireType = {FireElemental=true,BurningFist=true,FireMage=true}

local function updateLatestDeadMob(deadMob, cause)
    local level = RPD.Dungeon.level
    local hero = RPD.Dungeoheron
    local name = deadMob:getEntityKind()
    local counterId = name .."Kills"
    local prevAmount = storage.get(counterId) or 0
    storage.put(counterId, prevAmount+1)
    if ShadowType[name] then
        if math.random(1,100) <= 8 then
            level:drop(RPD.ItemFactory:itemByName("SoulShard"), deadMob:getPos())
        end
    end
    if IceType[name] then
        if math.random(1,100) <= 8 then
            level:drop(RPD.ItemFactory:itemByName("IceGuardianCoreModule"), deadMob:getPos())
        end
    end
    if SpiderType[name] then
        if math.random(1,100) <= 8 then
            level:drop(RPD.ItemFactory:itemByName("SpiderQueenCarapace"), deadMob:getPos())
        end
    end
    if FireType[name] then
        if math.random(1,100) <= 8 then
            level:drop(RPD.ItemFactory:itemByName("FrozenFlame"), deadMob:getPos())
        end
    end
end

mob.installOnDieCallback(updateLatestDeadMob)

return actor.init({
    act = function()
        local hero = RPD.Dungeon.hero
        local belongings = hero:getBelongings()
        time = time + 1
        if belongings.weapon then
            RPD.Dungeon.level:setCompassTarget(table.unpack(dungeonEntrance))
        else
            RPD.Dungeon.level:setCompassTarget(table.unpack(shopEntrance))
            if time - lastWarningTime > 10 then
                local heroPos = RPD.getXy(hero)
                local d2 = (dungeonEntrance[1] - heroPos[1])^2 + (dungeonEntrance[2] - heroPos[2])^2
                if d2 < 9 then
                    hero:interrupt()
                    lastWarningTime = time
                    local wnd = RPD.new(RPD.Objects.Ui.WndQuest,hero,RPD.textById("TownScript_NeedWeapon"))
                    RPD.GameScene:show(wnd)
                end
            end
        end
        return true
    end,
    actionTime = function()
        return 1
    end,
    activate = function()
        local level = RPD.Dungeon.level
        local hero = RPD.Dungeon.hero
        local levelSize = RPD.Dungeon.level:getLength()
        for i = 0 , levelSize - 1 do
            local emitter = RPD.Sfx.CellEmitter:get(i)
            emitter:pour(RPD.Sfx.SnowParticle.FACTORY, 2)
        end
        for i = 0, level:getLength() do
            local target = RPD.Actor:findChar(i)
            if target then
                if target ~= hero then
                    if target:hp() < 0 then
                        target:hp(1)
                    end
                end
            end
        end
    end
})