---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 02.05.19 14:36
---
local RPD  = require "scripts/lib/revampedCommonClasses"
local buff = require "scripts/lib/buff"

local immuneNormal = {"Hero","Roots","Paralysis","Vertigo","Invisibility","Levitation","Hunger","Poison","Frost","Light","Cripple","Charm","Blessed","MindVision","Necrotism","RageBuff","Amok","Awareness","Barkskin","Sleep","Slow","Blindness","Burning","Fury","Ooze","Combo","Speed","Terror","Shadows","Bleeding","Weakness","SnipersMark","Regeneration","CandleOfMindVisionBuff","BodyArmor","DieHard","Cloak","Counter","ShieldLeft","BlazingFiery","Charmful","SubZero","Fire","Foliage","ConfusionGas","LiquidFlame","ParalyticGas","Darkness","Web","ToxicGas","Regrowth","Freezing","Bounce","Stench","Affection","Potential","Viscosity","Metabolism","AntiEntropy","Displacement","Entanglement","Multiplicity","Fire","Luck","Slow","Death","Leech","Swing","Horror","Poison","Piercing","Paralysis","Instability","Ignite","Healing","WindGust","RootSpell","MagicTorch","FreezingGlobe","SummoningSpell","SummonDeathling","Dash","Cloak","Haste","Smash","DieHard","Possess","RaiseDead","Exhumation","DarkSacrifice","UndeadSummon","ElementalSummon","DeathlyRecruit","PotionOfExperience","PotionOfPurity","PotionOfToxicGas","PotionOfFrost","PotionOfParalyticGas","PotionOfHealing","PotionOfLiquidFlame","ManaPotion","PotionOfStrength","PotionOfMight","PotionOfInvisibility","PotionOfLevitation","PotionOfMindVision","ScrollOfUpgrade","ScrollOfTerror","ScrollOfChallenge","ScrollOfLullaby","ScrollOfRemoveCurse","ScrollOfCurse","ScrollOfMirrorImage","ScrollOfPsionicBlast","ScrollOfIdentify","ScrollOfDomination","ScrollOfSummoning","ScrollOfRecharging","ScrollOfTeleportation","ScrollOfWeaponUpgrade","ScrollOfMagicMapping","BlankScroll","WandOfMagicMissile","WandOfPoison","WandOfBlink","WandOfSlowness","WandOfFirebolt","WandOfIcebolt","WandOfFlock","WandOfLightning","WandOfTelekinesis","WandOfDisintegration","WandOfTeleportation","WandOfAmok","WandOfAvalanche","WandOfRegrowth","WandOfShadowbolt"}

local immuneAbnormal = {"Roots","Paralysis","Vertigo","Invisibility","Levitation","Hunger","Poison","Frost","Light","Cripple","Charm","Blessed","MindVision","Necrotism","RageBuff","Amok","Awareness","Barkskin","Sleep","Slow","Blindness","Burning","Fury","Ooze","Combo","Speed","Terror","Shadows","Bleeding","Weakness","SnipersMark","Regeneration","CandleOfMindVisionBuff","BodyArmor","DieHard","Cloak","Counter","ShieldLeft","BlazingFiery","Charmful","SubZero","Fire","Foliage","ConfusionGas","LiquidFlame","ParalyticGas","Darkness","Web","ToxicGas","Regrowth","Freezing","Bounce","Stench","Affection","Potential","Viscosity","Metabolism","AntiEntropy","Displacement","Entanglement","Multiplicity","Fire","Luck","Slow","Death","Leech","Swing","Horror","Poison","Piercing","Paralysis","Instability","Ignite","Healing","WindGust","RootSpell","MagicTorch","FreezingGlobe","SummoningSpell","SummonDeathling","Dash","Cloak","Haste","Smash","DieHard","Possess","RaiseDead","Exhumation","DarkSacrifice","UndeadSummon","ElementalSummon","DeathlyRecruit","PotionOfExperience","PotionOfPurity","PotionOfToxicGas","PotionOfFrost","PotionOfParalyticGas","PotionOfHealing","PotionOfLiquidFlame","ManaPotion","PotionOfStrength","PotionOfMight","PotionOfInvisibility","PotionOfLevitation","PotionOfMindVision","ScrollOfUpgrade","ScrollOfTerror","ScrollOfChallenge","ScrollOfLullaby","ScrollOfRemoveCurse","ScrollOfCurse","ScrollOfMirrorImage","ScrollOfPsionicBlast","ScrollOfIdentify","ScrollOfDomination","ScrollOfSummoning","ScrollOfRecharging","ScrollOfTeleportation","ScrollOfWeaponUpgrade","ScrollOfMagicMapping","BlankScroll","WandOfMagicMissile","WandOfPoison","WandOfBlink","WandOfSlowness","WandOfFirebolt","WandOfIcebolt","WandOfFlock","WandOfLightning","WandOfTelekinesis","WandOfDisintegration","WandOfTeleportation","WandOfAmok","WandOfAvalanche","WandOfRegrowth","WandOfShadowbolt"}

return buff.init{
    desc  = function ()
        return {
            icon          = 64,
            name          = "DmgImmune_Name",
            info          = "DmgImmune_Info",
        }
    end,

    defenceProc = function(chr, buff, enemy, dmg)
        return chr:damage(0, enemy)
    end,

    immunities = function(self, buff)
        if buff:getSource() then
            if buff.target:getMobClassName() == "FairyOverlordNPC" or buff.target:getMobClassName() == "FairyNPC" then
                return immuneAbnormal
            end
        end
        return immuneNormal
    end
}