---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 10/20/19 10:35 PM
---

local RPD  = require "scripts/lib/commonClasses"
local buff = require "scripts/lib/buff"
local storage = require "scripts/lib/storage"

return buff.init{
    icon = function(self, buff)
        if self.data.saved then
            return 55
        end
        return 56
    end,

    name = function(self, buff)
        if self.data.saved then
            return "FairySpellSaved_Name"
        end
        return "FairySpellNotSaved_Name"
    end,

    attachTo = function(self, buff, target)
        local saved = storage.get("FairyOverlord Saved") or false
        self.data.saved = self.data.saved or saved
        return true
    end,

    act = function(self,buff)
        RPD.BuffIndicator:refreshHero()
        buff:spend(1)
    end,

    charAct = function(self, buff)
        local level = RPD.Dungeon.level
        local user = buff.target
        local owner = "None"
        if self.data.saved then
            local vial = user:getBelongings():getItem("DewVial")
            if vial then
                if math.random(1,100) <= 3 then
                    if not vial:isFull() then
                        vial:collectDew(RPD.ItemFactory:itemByName("Dewdrop"))
                    end
                end
            end
        end
        for i = 0, level:getLength() do
            local target = RPD.Actor:findChar(i)
            if target then
                if target ~= RPD.Dungeon.hero then
                    if target:getOwner() then
                        owner = target:getOwner()
                    end
                end
                if target:getEntityKind() == "Fairy" then
                    if self.data.saved then
                        if owner then
                            local buffedId = target:name()..tostring(target:getId()).." buffed"
                            local buffed = storage.get(buffedId) or false
                            if not buffed then
                                target:ht(target:ht()*2)
                                target:hp(target:hp()*2)
                                RPD.setAi(target, "Hunting")
                                storage.put(buffedId, true)
                                buffed = storage.get(buffedId) or true
                            end
                            target:immunities():add(RPD.Buffs.Sleep)
                            target:immunities():add(RPD.Buffs.Paralysis)
                            target:immunities():add(RPD.Buffs.Amok)
                        else
                            target:destroy()
                            target:getSprite():killAndErase()
                        end
                    else
                        if not owner then
                            local buffedId = target:name()..tostring(target:getId()).." buffed"
                            local buffed = storage.get(buffedId) or false
                            if not buffed then
                                target:ht(target:ht()*2)
                                target:hp(target:hp()*2)
                                RPD.setAi(target, "Hunting")
                                storage.put(buffedId, true)
                                buffed = storage.get(buffedId) or true
                            end
                            target:immunities():add(RPD.Buffs.Sleep)
                            target:immunities():add(RPD.Buffs.Paralysis)
                            target:immunities():add(RPD.Buffs.Amok)
                        end
                    end
                end
            end
        end
    end
}
