---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 02.05.19 14:36
---
local RPD  = require "scripts/lib/revampedCommonClasses"
local buff = require "scripts/lib/buff"
local storage = require "scripts/lib/storage"

local Debuff = {"Burning","Frost","Slown","Sleep","Blindness","Paralysis","Bleeding","Roots","Vertigo","SubZero","Nightmare","Charm","Hunger","Poison","Cripple","Necrotism","Amok","Ooze","Terror","Weakness","FairySpell"}

return buff.init{
    desc  = function ()
        return {
            icon          = 42,
            name          = "God Mode",
            info          = "God Mode for testing.",
        }
    end,

    attachTo = function(self, buff, target)
        return true
    end,

    detach = function(self, buff)
        buff.target.viewDistance = 1
    end,

    act = function(self,buff)
        buff:spend(1)
    end,

    defenceProc = function(chr, buff, enemy, dmg)
        local chr = buff.target
        local chrKind = enemy:getEntityKind()
        local debuff = storage.get("RemoveDebuffs") or false
        if debuff then
            for i = 1, #Debuff do
                if chr:buffLevel(Debuff[i]) > 0 then
                    if Debuff[i] ~= "FairySpell" or (Debuff[i] == "FairySpell" and storage.get("FairyOverlord Saved") == false) then
                        RPD.removeBuff(chr, Debuff[i])
                    end
                end
            end
        end
        RPD.glogn(RPD.MobFactory:mobByName(chrKind):name().." has delt "..tostring(dmg).." damage to "..chr:name()..".")
        return 0
    end,

    attackProc = function(chr, buff, enemy, dmg)
        local chr = buff.target
        local chrKind = enemy:getEntityKind()
        local debuff = storage.get("RemoveDebuffs") or false
        local grammar
        if chr:name() == "you" then
            grammar = "have"
        else
            grammar = "has"
        end
        if debuff then
            for i = 1, #Debuff do
                if chr:buffLevel(Debuff[i]) > 0 then
                    if Debuff[i] ~= "FairySpell" or (Debuff[i] == "FairySpell" and storage.get("FairyOverlord Saved") == false) then
                        RPD.removeBuff(chr, Debuff[i])
                    end
                end
            end
        end
        RPD.glogp(chr:name().." "..grammar.." delt "..tostring(dmg).." damage to "..RPD.MobFactory:mobByName(chrKind):name()..".")
        return dmg
    end,

    charAct = function(chr, buff)
        local level = RPD.Dungeon.level
        local chr = buff.target
        local debuff = storage.get("RemoveDebuffs") or false
        chr.viewDistance = level:getMaxViewDistance()
        if debuff then
            for i = 1, #Debuff do
                if chr:buffLevel(Debuff[i]) > 0 then
                    if Debuff[i] ~= "FairySpell" or (Debuff[i] == "FairySpell" and storage.get("FairyOverlord Saved") == false) then
                        RPD.removeBuff(chr, Debuff[i])
                    end
                end
            end
        end
        chr:heal(chr:ht(), chr)
        if chr:name() == "you" then
            chr:setSoulPoints(chr:getSkillPointsMax())
            chr:hunger():satisfy(chr:hunger():getHungerLevel())
        end
    end
}
