---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 02.05.19 14:36
---

local RPD = require "scripts/lib/revampedCommonClasses"
local buff = require "scripts/lib/buff"

return buff.init{
    desc  = function ()
        return {
            icon          = 54,
            name          = "NightmareBuff_Name",
            info          = "NightmareBuff_Info",
        }
    end,

    attachTo = function(self, buff, target)
        return true
    end,

    detach = function(self, buff)
    end,

    act = function(self, buff)
        buff:spend(1)
    end,

    charAct = function(self, buff)
        buff.target:hp(buff.target:hp()-1)
        buff.target:getSprite():showStatus(0xFF0000, "1")
    end
}
