---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 02.05.19 14:36
---
local RPD  = require "scripts/lib/revampedCommonClasses"
local buff = require "scripts/lib/buff"

local Water = {[50]=true,[51]=true,[52]=true,[53]=true,[54]=true,[55]=true,[56]=true,[57]=true,[58]=true,[59]=true,[60]=true,[61]=true,[62]=true,[63]=true}

return buff.init{
    desc  = function ()
        return {
            icon          = 53,
            name          = "SubZeroBuff_Name",
            info          = "SubZeroBuff_Info",
        }
    end,

    attachTo = function(self, buff, target)
        return true
    end,

    detach = function(self, buff)
    end,

    act = function(self,buff)
        buff:spend(1)
    end,

    charAct = function(chr,buff)
        local chr = buff.target
        local level = RPD.Dungeon.level
        local dmg = 0
        if Water[level.map[chr:getPos()]] or chr:buffLevel(RPD.Buffs.Frost) > 0 then
            dmg = math.random(13,18)
        else
            dmg = math.random(3,6)
        end
        if dmg >= chr:hp() then
            chr:damage(dmg, buff)
        else
            chr:hp(chr:hp()-dmg)
            buff.target:getSprite():showStatus(0xFF0000, tostring(dmg))
        end
    end
}
