---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 23.08.18 22:51
---

local RPD = require "scripts/lib/revampedCommonClasses"

local ai = require "scripts/lib/ai"

local raw = {
    MysteryMeat = true,
    RawFish = true,
    FrozenCarpaccio = true,
    FrozenFish = true
}

return ai.init{

    act = function(self, ai, me)
        local level = RPD.Dungeon.level
        local heaps = level:allHeaps()
        local iterator = heaps:iterator()
        while iterator:hasNext() do
            local heap = iterator:next()
            local itemPos = heap.pos
            if level.fieldOfView[itemPos] then
                local item = heap:peek()
                if raw[item:getClassName()] then
                    if level:adjacent(itemPos, me:getPos()) then
                        RPD.Wands.wandOfFirebolt:mobWandUse(me, itemPos)
                        break
                    else
                        local tgt = level:getEmptyCellNextTo(itemPos)
                        if level:cellValid(tgt) then
                            RPD.blinkTo(me, tgt)
                            break
                        end
                    end
                end
            end
        end
        me:spend(1)
    end,

    gotDamage = function(self, ai, me, src, dmg)
    end,

    status = function(self, ai, me)
        return "_Monika_ is messing with the unknown"
    end
}