---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mike.
--- DateTime: 11/5/19 11:02 PM
---


local stats = {}

stats.strForLevel    = {10, 12, 14, 16, 18, 20}
stats.chanceForLevel = {.2, .3, .4, .4, .5, .6}
stats.blockForLevel  = {2, 4, 6, 8, 10, 12}

return stats